### ISSUE TITLE
May I know where the Windows model will be downloaded to?

### ISSUE THREAD

**Issue by c469591** [karaokenerds/python-audio-separator#14]
Hello, I would like to know where the model will be downloaded in Windows. I can't find it. Thank you.

**Comment by beveradb** [comment]
Sorry, I don't use Windows so have no idea what happens when something tries to write files to `/tmp` (the default directory is `/tmp/audio-separator-models/`)

If you run in debug mode (`--log_level=debug` parameter if you're using it on the command line) it should print the path it's writing to, but you can also customise this using the `--model_file_dir` parameter.
