### ISSUE TITLE
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 6

### ISSUE THREAD

**Issue by bbangka** [karaokenerds/python-audio-separator#15]
Hi, when I run the separator on 24 mins long m4a file, I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/audio-separator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/audio_separator/utils/cli.py", line 112, in main
    output_files = separator.separate()
  File "/usr/local/lib/python3.9/dist-packages/audio_separator/separator.py", line 193, in separate
    source = self.demix_base(mix)[0]
  File "/usr/local/lib/python3.9/dist-packages/audio_separator/separator.py", line 271, in demix_base
    mix_waves, pad = self.initialize_mix(mix_p, is_ckpt=is_ckpt)
  File "/usr/local/lib/python3.9/dist-packages/audio_separator/separator.py", line 254, in initialize_mix
    mix_p = np.concatenate((np.zeros((2, self.trim)), mix, np.zeros((2, pad)), np.zeros((2, self.trim))), 1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 6

When I print out $mix value, I get 
mix =
[[ 0.000000e+00  0.000000e+00  0.000000e+00 ...  0.000000e+00
   0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 ...  0.000000e+00
   0.000000e+00  0.000000e+00]
 [ 9.408713e-09 -9.586301e-09  8.488125e-09 ... -2.402059e-06
   1.561118e-06  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 ...  0.000000e+00
   0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 ...  0.000000e+00
   0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 ...  0.000000e+00
   0.000000e+00  0.000000e+00]]
[[0. 0. 0. ... 0. 0. 0.]

It seems like $mix is supposed to be a 2 x n matrix, but it has 6 x n matrix instead. 

Do you know how to resolve this issue? The script doesn't really print other messages in debug mode.

**Comment by beveradb** [comment]
That's a weird one, never seen that before! Are you able to share a test file for me to reproduce?

**Comment by beveradb** [comment]
> Hi bebvradb, the file is bigger than 25 mb, so I can't upload here. What is the best way to share the file with you?

ah fair point, sorry - here's a dropbox request link: https://www.dropbox.com/request/8enj569WRN8JTVHB8HUy

**Comment by beveradb** [comment]
Hey @bbangka, you didn't upload the example file so I was never able to reproduce this issue.

However, I believe the only way that could have occurred is if the audio file you're trying to separate has 6 channels (e..g surround sound) rather than just 2 channels (stereo).

I've just added an explicit check / error handling for that, along with much more verbose debug logging to that `initialize_mix` method: https://github.com/karaokenerds/python-audio-separator/commit/36f28de8c4adf3cdc3c40c0d2ca2deaa76615cf4

`audio-separator` doesn't currently support more than 2 channels, so if you wanted to separate your 5.1 channel surround sound audio file you'd first need to downmix it to stereo.
That's something which is built-in functionality in `ffmpeg` and documented well here: https://trac.ffmpeg.org/wiki/AudioChannelManipulation#a5.1stereo

So all you probably need to do is run this to downmix to stereo:
`ffmpeg -i yourfile.m4a -ac 2 yourfile.wav`

Then use that stereo file as your input:
`audio-separator yourfile.wav`

If this doesn't work for you, or you have any other issues feel free to re-open the issue!
