### ISSUE TITLE
Kim Vocal2 instrumental music contains vocal sound. But UVR GUI doesn't 

### ISSUE THREAD

**Issue by hijaek** [karaokenerds/python-audio-separator#22]
I tested with multiple songs using the same model "Kim Vocal 2"

the instrumental file from UVR GUI does not have any vocals left, but python-audio-separator contains significant amount of vocals left in the instrument.

I tested it both locally and on my aws server, but whenever I use python-audio-separator's Kim Vocal 2, I keep getting the same result.

Has anyone else had the same issue?

**Comment by ajayarora1235** [comment]
ooh yes I am running into this. unfortunately i noticed it after processing a bunch of audio tracks :/ will have to redo them with the MDX-HQ models

**Comment by beveradb** [comment]
Hey @hijaek / @ajayarora1235 , thanks for trying `audio-separator` and for reaching out!
Sorry for the slow reply on this, didn't have much capacity for hobby projects till now.

Please could you provide your log output with `--log_level debug`?

Could you try and see if there is any difference with `--denoise=False` vs. `--denoise=True`, or with `--single_stem=instrumental`?

Later today I'm going to be working on trying to identify changes to UVR since I first extracted logic out into this project 6 months ago, so I may well be able to get to the bottom of differences like this.

Investigation from yourselves is of course encouraged, and if either of you manage to figure it out, please raise a pull request with a fix!

**Comment by beveradb** [comment]
Hey @hijaek / @ajayarora1235 - please could you try with the latest version of `audio-separator` (0.14 or newer) or provide a test audio file for me to compare with UVR?

If I don't hear from either of you in the next week or two I'll close this issue as fixed, as I'm pretty optimistic the issue should've been resolved in one of the versions over the last 4 months :)

**Comment by ajayarora1235** [comment]
this got fixed!

**Comment by beveradb** [comment]
Thank you for confirming @ajayarora1235 !

I'll close this now 😄
