### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by Tiaranso** [karaokenerds/python-audio-separator#44]
```
def _vocal_instrumental_remover(name_file:str):
    from audio_separator.separator import Separator
    separator = Separator()
    separator.load_model('UVR-MDX-NET-Inst_HQ_3')
    primary_stem_path, secondary_stem_path = separator.separate(f"temp_file/{name_file}/{name_file}.wav")
    print(f'Primary stem saved at {primary_stem_path}')
    print(f'Secondary stem saved at {secondary_stem_path}')
    return {"primary": primary_stem_path, "secondary": secondary_stem_path}

if __name__ == "__main__":
    print(_vocal_instrumental_remover(name_file="1-1708443014-635058"))
```

```
024-02-21 08:40:19,232 - DEBUG - separator - STFT applied on mix. Spectrum shape: torch.Size([1, 4, 3072, 256])
2024-02-21 08:40:32,414 - DEBUG - separator - Model run on the spectrum without denoising.
2024-02-21 08:40:32,778 - DEBUG - separator - Inverse STFT applied. Returning result with shape: (1, 2, 261120)
2024-02-21 08:40:32,780 - DEBUG - separator - Normalizing result by dividing result by divider.
/usr/local/lib/python3.10/dist-packages/audio_separator/separator/separator.py:657: RuntimeWarning: invalid value encountered in divide
  tar_waves = result / divider
Killed
```

Congratulations. This is the problem with one-hour videos. After all the chunks, the console displays the text "Killed" and that's it. How can I fix it? Operating system Ubuntu, CPU.

**Comment by beveradb** [comment]
Hey @Tiaranso , sorry you had that experience, I can imagine that was quite frustrating 😞 
Not sure what you mean by congratulations, though?

I'm pretty confident the unhelpful "Killed" message comes from the Linux kernel OOM (Out of Memory) killer, which is a feature built into all Linux systems to kill processes as a last resort when the system is running out of memory.
You can learn more about it here:
- https://www.kernel.org/doc/gorman/html/understand/understand016.html
- https://neo4j.com/developer/kb/linux-out-of-memory-killer/
- https://sematext.com/glossary/linux-out-of-memory-killer/
- https://medium.com/@adilrk/linux-oom-out-of-memory-killer-74fbae6dc1b0

This makes sense, as `audio-separator` does use a fair bit of memory to run the inference process on an input audio file, and if you're running it on an hour-long file, it's going to use a lot of memory!

Exactly _how much_ memory it uses depends on a number of variables, e.g. the input audio file, which model you're using, and what parameters you pass in, e.g. `mdx_batch_size` or `vr_batch_size` in particular.

I don't have all of the information to be able to tell you 100% what the best solution for you is (e.g. I don't know what version of `audio-separator` you're using, how much memory your system has, and I don't have the input file to test different parameters myself to help you). The first part of the log output from audio-separator is generally quite useful compared to the last few lines, as it logs some info about your system and separation parameters.

However, even without more info, I can suggest a few options:
1) Upgrade `audio-separator` and try again; it looks like you're using quite an old version and some things have improved since that, e.g. there's now better garbage collection between segment inference which means less memory usage.

2) Run the latest version of `audio-separator` again for the same input file from the CLI, and monitor your system memory usage (e.g. with `htop`) to get a feel for how much memory the process is using. 
  - Recent audio-separator versions output a progress bar so you can see how far along the separation process is.
  - The progress bar, combined with `htop` should allow you to see how quickly your system memory is being consumed, which can help steer towards different solutions.
  - For example, if you can see that audio-separator gets close to 90% complete before it gets killed by the system OOM killer, you can probably resolve this by reducing the config parameter `mdx_segment_size` a bit.
3) Try a different model; you can see a list of all supported models by running `audio-separator --list_models`.
  - For example, since you were using `UVR-MDX-NET-Inst_HQ_3.onnx`, I can recommend trying `2_HP-UVR.pth` which I find performs very similarly but about twice as fast as the MDX model.
4) If you're still getting OOM killer issues on your system even after upgrading to the latest version, trying different models, and tweaking parameters, you might have to accept that your system doesn't have enough RAM to separate the whole file in one go. At this point, my recommendation would be to use ffmpeg to cut the file into 2 parts, separate them both independently, then join them again.

If you end up following the final (last resort) option of splitting into separate parts, separating, and rejoining, here's an example of how you could achieve that using a python script, executing ffmpeg with pydub:

```
from pydub import AudioSegment


def split_audio_into_two_halves(input_file):
    print(f"Starting to split audio file: {input_file} into two halves.")
    audio = AudioSegment.from_wav(input_file)
    halfway_point = len(audio) // 2
    part1 = audio[:halfway_point]
    part2 = audio[halfway_point:]

    output_files = [f"{input_file}-part1.wav", f"{input_file}-part2.wav"]
    part1.export(output_files[0], format="wav")
    part2.export(output_files[1], format="wav")
    print(f"Audio file: {input_file} has been split into: {output_files[0]} and {output_files[1]}")
    return output_files[0], output_files[1]


def separate_stems(input_file, model_filename="UVR-MDX-NET-Inst_HQ_3.onnx"):
    print(f"Starting to separate stems from file: {input_file} using model: {model_filename}")
    from audio_separator.separator import Separator

    separator = Separator()
    separator.load_model(model_filename)
    primary_stem_output_path, secondary_stem_output_path = separator.separate(input_file)
    return primary_stem_output_path, secondary_stem_output_path


def join_audio(part1_path, part2_path, output_filename):
    print(f"Starting to join audio files: {part1_path} and {part2_path} into {output_filename}")
    combined = AudioSegment.empty()

    audio_part1 = AudioSegment.from_file(part1_path)
    audio_part2 = AudioSegment.from_file(part2_path)
    combined += audio_part1 + audio_part2

    combined.export(output_filename, format="wav")
    print(f"Audio files: {part1_path} and {part2_path} have been joined into {output_filename}")
    return output_filename


def _vocal_instrumental_remover(name_file: str):
    input_filename = f"temp_file/{name_file}/{name_file}.wav"

    part1_wav, part2_wav = split_audio_into_two_halves(input_filename)
    part1_primary_stem_path, part1_secondary_stem_path = separate_stems(part1_wav)
    part2_primary_stem_path, part2_secondary_stem_path = separate_stems(part2_wav)

    primary_stem_path = join_audio(part1_primary_stem_path, part2_primary_stem_path, f"temp_file/{name_file}/{name_file}-primary.wav")
    secondary_stem_path = join_audio(part1_secondary_stem_path, part2_secondary_stem_path, f"temp_file/{name_file}/{name_file}-secondary.wav")

    print(f"Primary stem saved at {primary_stem_path}")
    print(f"Secondary stem saved at {secondary_stem_path}")
    return {"primary": primary_stem_path, "secondary": secondary_stem_path}


if __name__ == "__main__":
    print(_vocal_instrumental_remover(name_file="1-1708443014-635058"))

```

Hope this helps!

**Comment by Tiaranso** [comment]
Yes, thank you for your help. I've improved the code a bit and instead of dividing the audio into two parts, I divide it into 4 minute parts. This prevents errors, but it takes a lot of time to process. 

```
from pydub import AudioSegment
import os


def split_audio_into_segments(input_file, name_file, segment_length_ms=240000):
    print(f"Starting to split audio file: {input_file} into segments of {segment_length_ms} milliseconds.")
    audio = AudioSegment.from_wav(input_file)
    segment_count = len(audio) // segment_length_ms
    output_files = []

    if not os.path.exists(f"temp_file/{name_file}/segments"):
        os.makedirs(f"temp_file/{name_file}/segments")

    for i in range(segment_count):
        segment_start = i * segment_length_ms
        segment_end = (i + 1) * segment_length_ms
        segment = audio[segment_start:segment_end]
        output_file = f"temp_file/{name_file}/segments/segment{i + 1}.wav"
        segment.export(output_file, format="wav")
        output_files.append(output_file)

    print(f"Audio file: {name_file} has been split into {segment_count} segments.")
    return output_files



def separate_stems(input_file, model_filename="UVR-MDX-NET-Inst_HQ_3.onnx"):
    print(f"Starting to separate stems from file: {input_file} using model: {model_filename}")
    from audio_separator.separator import Separator

    separator = Separator()
    separator.load_model(model_filename)
    primary_stem_output_path, secondary_stem_output_path = separator.separate(input_file)
    return primary_stem_output_path, secondary_stem_output_path


def join_audio(segments, output_filename):
    print(f"Starting to join audio files: {segments} into {output_filename}")

    combined = AudioSegment.empty()
    for segment in segments:
        combined += AudioSegment.from_file(segment)
    combined.export(output_filename, format="wav")

    print(f"Audio files: have been joined into {output_filename}")
    return output_filename


def _vocal_instrumental_remover(name_file: str):
    input_filename = f"temp_file/{name_file}/{name_file}.wav"

    part1_primary_stem_path_array = []
    part1_secondary_stem_path_array = []

    segments = split_audio_into_segments(input_filename, name_file)
    for i in range(len(segments)):
        part1_primary_stem_path, part1_secondary_stem_path = separate_stems(f"temp_file/{name_file}/segments/segment{i + 1}.wav")
        part1_primary_stem_path_array.append(part1_primary_stem_path)
        part1_secondary_stem_path_array.append(part1_secondary_stem_path)

    primary_stem_path = join_audio(part1_primary_stem_path_array, f"temp_file/{name_file}/primary.wav")
    secondary_stem_path = join_audio(part1_secondary_stem_path_array, f"temp_file/{name_file}/secondary.wav")

    print(f"Primary stem saved at {primary_stem_path}")
    print(f"Secondary stem saved at {secondary_stem_path}")
    return {"primary": primary_stem_path, "secondary": secondary_stem_path}


if __name__ == "__main__":
    print(_vocal_instrumental_remover(name_file="1-1708443014-635058"))
```

Now I want to try to rent a GPU server and run the code on it. If you are interested, I can share the result later.

**Comment by beveradb** [comment]
Thanks for confirming! 
I might go ahead and add a feature to `audio-separator` to do this (split up long input files into smaller files of max duration before attempting separation, rejoin afterwards) - would probably be useful for anyone else like you trying to use it on larger inputs with constrained resources!

Yeah, you should find things are a bit faster on a GPU for sure. Most of my usage is on my local machine but that's still GPU-accelerated since I'm using an apple silicon macbook.

Have you tried other models? You might find `2_HP-UVR.pth` gives you equally decent results in about half the time compared to `UVR-MDX-NET-Inst_HQ_3.onnx`!
