### ISSUE TITLE
Demixing %100 Cpu Usage

### ISSUE THREAD

**Issue by cometothed4rkside** [karaokenerds/python-audio-separator#5]
Hello, gpu is active but it uses 100% cpu during demixing phase.

model_name: UVR_MDXNET_KARA_2, output_dir: None, use_cuda: True, output_format: WAV
2023-07-31 04:35:40,379 - DEBUG - separator - CUDA requested, checking Torch version and CUDA status
2023-07-31 04:35:40,379 - DEBUG - separator - Torch version: 2.0.0+cu118
2023-07-31 04:35:40,393 - DEBUG - separator - Is CUDA enabled? True
2023-07-31 04:35:40,393 - DEBUG - separator - Running in GPU mode
2023-07-31 04:35:40,393 - DEBUG - separator - Reading model settings...

**Comment by JustinOsu** [comment]
I found a simple fix for that. If you want to run it on GPU you need to:
1. uninstall onnxruntime
2. uninstall onnxruntime-gpu
3. install optimum[onnxruntime-gpu]

check this documentation for more info: 
https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/gpu#installation

**Comment by beveradb** [comment]
Hey, sorry for the inconvenience around this, I hadn't really been able to test GPU support myself till now.

With version 0.6.4, I've now added clear instructions for GPU users to the README:
https://github.com/karaokenerds/python-audio-separator#extra-installation-steps-for-use-with-a-gpu

Thanks @JustinOsu for the specific instructions!

I've tested it myself on a [runpod instance with a GPU](https://www.runpod.io/console/gpu-cloud) and wow, separation literally takes a few seconds rather than a few minutes 😅 

So, hopefully with clear instructions in the README, it's fair to close this?

If you or anyone else knows how to package/publish so this would work out of the box for GPU users and CPU users on any platform without extra installation steps, please let me know!
