### ISSUE TITLE
cuda12.0 is available? 

### ISSUE THREAD

**Issue by chicumt** [karaokenerds/python-audio-separator#69]
I download the GPU version,but it is still work on cpu,and my cuda is 12.0

**Comment by chicumt** [comment]
it default download the torch with cpu, and i change it to cuda version,but some problems as follow
![image](https://github.com/karaokenerds/python-audio-separator/assets/99591215/99866ceb-4fe0-4e94-96f8-6ff361d9cbd1)

**Comment by beveradb** [comment]
Hey @chicumt, 

It looks like you're seeing the same error as this person: https://github.com/karaokenerds/python-audio-separator/issues/70

Please could you clarify what the issue was and how you resolved it?

I don't have a Windows machine or an Nvidia GPU to test with myself (and even if I did, I can't stand Windows so wouldn't want to 😅) so would appreciate you sharing knowledge with others! 🙇
