### ISSUE TITLE
UVR-DeEcho-DeReverb Support

### ISSUE THREAD

**Issue by quicksandznzn** [karaokenerds/python-audio-separator#9]
Seem to only support ONNX Model , UVR-DeEcho-DeReverb Is PyTorch Model , How Convert UVR-DeEcho-DeReverb to ONNX Model, Or Support PyTorch Model Load

**Comment by beveradb** [comment]
Hey, the simple answer is I haven't implemented support for any other kind of model as the MDX-Net models (using ONNX Runtime) work well for me.

I do understand that UVR has support for a variety of model formats but I initially wanted to keep this codebase a lot simpler than the [tangled mess of separation code in UVR](https://github.com/Anjok07/ultimatevocalremovergui/blob/master/separate.py) - and part of that was being selective about what to support.

In my opinion, the MDX-Net ONNX models are the state of the art for **audio separation** (the focus of this project), so I'm not wild about increasing the complexity of this code in order to support other model types unless there's a much better model for **audio separation** in a different format.

All of this said, though - PRs are very much welcome, if you want to add support for other model formats to this code please do! 😄 
I would just request that you try and keep things a bit more organized & separate than the way things are done in UVR - e.g. don't have everything in one file! 😅

**Comment by quicksandznzn** [comment]
OK I GOT IT
